### ISSUE TITLE
Motion planning based on end-effector start-goal in cartesian space. 

### ISSUE THREAD

**Issue by pushkalkatara** [yijiangh/pybullet_planning#7]
Hi, 

Thanks for the amazing library over pybullet.

Is there a way to provide start and goal pair of end-effector of the arm in cartesian space and generate a motion plan with support for obstacle avoidance?

The current planner takes the end configuration of the arm as input in joint-space, but I wanted to give start-goal input in cartesian space.

Thanks

**Comment by yijiangh** [comment]
@pushkalkatara Yes! You can use [`plan_cartesian_motion`](https://github.com/yijiangh/pybullet_planning/blob/dev/src/pybullet_planning/interfaces/planner_interface/cartesian_motion_planning.py#L30), and you have to do collision checking yourself after a trajectory is found by using [`get_collision_fn`](https://github.com/yijiangh/pybullet_planning/blob/dev/src/pybullet_planning/interfaces/robots/collision.py#L338). 

You can find an example [here](https://github.com/yijiangh/compas_fab_pychoreo/blob/yh/itj/src/compas_fab_pychoreo/backend_features/pychoreo_plan_cartesian_motion.py#L110-L120).

**Comment by nickredsox** [comment]
The example link is dead. Do you have any other links to an example of this?

**Comment by yijiangh** [comment]
@nickredsox https://github.com/yijiangh/pybullet_planning/blob/dev/tests/test_cartesian.py#L80

**Comment by SageRobots** [comment]
How do we get the ikfast_kuka_kr6_r900 module for that example?
ModuleNotFoundError: No module named 'ikfast_kuka_kr6_r900'

**Comment by yijiangh** [comment]
@SageRobots : https://github.com/yijiangh/ikfast_pybind
